Init commit
Al-Sher/otus_anti_bruteforce pull request #1
Opened 2023-07-26 05:35 UTC by Al-Sher

2023-07-26 19:09 UTC, dshemin requested changes

2023-07-26 19:09 UTC, dshemin commented on cmd/anti-bruteforce/main.go
> +	ctx, cancel := signal.NotifyContext(ctx, syscall.SIGINT, syscall.SIGTERM, syscall.SIGHUP)
Важно:

Это надо было сделать выше. Сразу после создания контекста.

2023-07-26 19:09 UTC, dshemin commented on cmd/cli/main.go
> +	ctx := context.Background()
Важно:

Особого смысла в таком контексте нет. Он ничего не даёт. Либо убрать, либо добавить signal.NotifyContext.

2023-07-26 19:09 UTC, dshemin commented on cmd/cli/main.go
> +	if err := hc.Get(ctx, "blackList", vs); err != nil {
Важно:

Копипаста, наверное всё же whitelist.

2023-07-26 19:09 UTC, dshemin commented on internal/config/config.go
> +type Config struct {
Совет:

Для проекта - нормально. Но всё же посмотрите в сторону уже готовых пакетов типа https://github.com/spf13/viper, https://github.com/kelseyhightower/envconfig, и т.п.

2023-07-26 19:09 UTC, dshemin commented on internal/config/config.go
> +	return cfg, nil
Важно:

Нет валидации конфига.

2023-07-26 19:09 UTC, dshemin commented on internal/httpclient/httpClient.go
> +func (h *httpClient) Get(ctx context.Context, endpoint string, params url.Values) error {
Важно:

GET запрос в семантике HTTP подразумевает что мы что-то запрашиваем и получаем. В данном случае мы нечего не возвращаем. Такое чувство что вы спутали если с POST, PATCH, PUT или DELETE методом.

2023-07-26 19:09 UTC, dshemin commented on internal/httpclient/httpClient.go
> +	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, h.buildURL(endpoint, params), nil)
Важно:

При беглом взгляде все три метода абсолютно идентичны за исключением используемого метода. Стоит вынести общую часть в отдельный метод, а все специфичные части передавать в аргументах.

2023-07-26 19:09 UTC, dshemin commented on internal/server/server.go
> +	err := s.srv.ListenAndServe()
Важно:

Что будет если порт, на который мы биндимся уже занят? Наше приложение не запустит HTTP сервер и повиснет?

2023-07-26 19:09 UTC, dshemin commented on internal/ratelimit/rt.go
> +	okLogin := r.loginBucket.Check(login)
Важно:

Если мы уже поняли что по логину нельзя, зачем нам делать дополнительные вычисления, которые не бесплатны?

2023-07-26 19:09 UTC, dshemin commented on internal/ratelimit/rt.go
> +	r.loginBucket.ResetKey(login)
Важно:

А как нам ресетнуть пароль?

2023-07-26 19:09 UTC, dshemin commented on cmd/cli/main.go
> +	if err := hc.Get(ctx, "blackList", vs); err != nil {
Критично:

Делаем GET запрос, но сервер его не принимает. Для blacklist и whitelist у нас доступны POST и DELETE.

2023-07-26 19:09 UTC, dshemin commented on pkg/bucket/bucket.go
> +		t = token
Важно:

Можно просто написать вот так:
```
token, ok := b.tokens[key]
if !ok {
   // Достигнут лимит корзины.
   // ...
}
```
И тогда м можем избавиться от этого ненужного else

2023-07-26 19:32 UTC, Al-Sher commented on internal/ratelimit/rt.go
> +	okLogin := r.loginBucket.Check(login)
Чтобы счетчик попыток по паролю и ip увеличился

2023-07-26 19:34 UTC, Al-Sher commented on internal/ratelimit/rt.go
> +	r.loginBucket.ResetKey(login)
В техническом задании указано, что сбрасывать нужно только по login и ip, насколько понял.
https://github.com/OtusGolang/final_project/blob/master/01-anti-bruteforce.md#%D1%81%D0%B1%D1%80%D0%BE%D1%81-bucket

2023-07-29 06:13 UTC, Al-Sher commented on cmd/anti-bruteforce/main.go
> +	ctx, cancel := signal.NotifyContext(ctx, syscall.SIGINT, syscall.SIGTERM, syscall.SIGHUP)
Поправил. Но это требует отключение линтера gocritic при выходе из приложения с ошибкой, где отмена контекста не влияет на завершения приложения(нет пользовательских запросов и graceful shutdown не нужен)

2023-07-29 06:15 UTC, Al-Sher commented on cmd/cli/main.go
> +	ctx := context.Background()
Убрал

2023-07-29 06:16 UTC, Al-Sher commented on cmd/cli/main.go
> +	if err := hc.Get(ctx, "blackList", vs); err != nil {
Переписал

2023-07-29 06:18 UTC, Al-Sher commented on internal/config/config.go
> +	return cfg, nil
Добавил валидацию

2023-07-29 06:19 UTC, Al-Sher commented on internal/server/server.go
> +	err := s.srv.ListenAndServe()
Поправил

2023-07-29 06:19 UTC, Al-Sher commented on cmd/cli/main.go
> +	if err := hc.Get(ctx, "blackList", vs); err != nil {
Поправил

2023-07-29 06:19 UTC, Al-Sher commented on pkg/bucket/bucket.go
> +		t = token
Поправил

2023-07-30 16:47 UTC, merged